name: CICD-PPK3

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [8.3]

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: pusatpelatihank3
          MYSQL_USER: adminpusatk3
          MYSQL_PASSWORD: securepass123
          MYSQL_ROOT_PASSWORD: rootpassword
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping --host=127.0.0.1 --user=adminpusatk3 --password=securepass123" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP ${{ matrix.php-version }}
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}
        extensions: mbstring, xml, ctype, json, pdo, pdo_mysql, bcmath, fileinfo

    - name: Install Dependencies
      run: composer install --prefer-dist --optimize-autoloader

    - name: Setup Environment
      run: |
        cp .env.example .env
        php artisan key:generate
        php artisan config:clear
        php artisan cache:clear

        # Konfigurasi database untuk GitHub Actions
        echo "DB_CONNECTION=mysql" >> .env
        echo "DB_HOST=127.0.0.1" >> .env
        echo "DB_PORT=3306" >> .env
        echo "DB_DATABASE=pusatpelatihank3" >> .env
        echo "DB_USERNAME=adminpusatk3" >> .env
        echo "DB_PASSWORD=securepass123" >> .env
        echo "DB_SOCKET=" >> .env  # Pastikan MySQL tidak menggunakan socket default

    - name: Tunggu MySQL Siap
      run: sleep 15  # Memberikan waktu agar MySQL bisa benar-benar siap

    - name: Run Migrations
      run: php artisan migrate --force  # Jalankan migrasi sebelum testing

    - name: Run Tests
      run: vendor/bin/phpunit

  deploy-staging:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: Deploy to Staging via SSH
      uses: appleboy/ssh-action@v1.2.1
      with:
        host: ${{ secrets.HOST }}
        username: lenovo
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          ./deploy-pusat-pelatihan-k3.sh
        debug: true
